# Generated by Django 5.2.8 on 2026-01-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_options_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Имя которое будут видеть другие пользователи (можно оставить пустым)', max_length=100, verbose_name='Отображаемое имя'),
        ),
    ]
